from itblib.globals.Enums import PHASES

STANDARD_TILE_SIZE = (64, 96)
STANDARD_UNIT_SIZE = (64, 64)

class HUD:
    IMAGE_BORDER_WIDTH = 2
    LABEL_HEIGHT = 22
    ELEM_WIDTH = 200
    TITLE_FONT_SIZE = 32
    DESC_FONT_SIZE = 16
    SMALL_FONT_SIZE = 12

    class TILEDISPLAY:
        IMAGE_SIZE = STANDARD_TILE_SIZE


class FLAGS:
    MOVEMENT_DEFAULT  = 0b001
    MOVEMENT_WATER    = 0b010
    MOVEMENT_MOUNTAIN = 0b100

class PHASE_DURATIONS:
    # Keys are itblib.globals.Enums.PHASES, values are durations in seconds 
    DURATIONS = {
        PHASES.PREGAMEPHASE :20,
        PHASES.PLANNINGPHASE:10,
        PHASES.PREPHASE     : 0,
        PHASES.BATTLEPHASE  : 0,
        PHASES.POSTPHASE    : 0
    }

class PHASE_NAMES:
    NAMES = {
        PHASES.PREGAMEPHASE :"Pregamephase" , 
        PHASES.PLANNINGPHASE:"Planningphase",
        PHASES.PREPHASE     :"Prephase"     ,     
        PHASES.BATTLEPHASE  :"Battlephase"  ,  
        PHASES.POSTPHASE    :"Postphase"
    }

class DIRECTIONS:
    NORTH = (-1,-1)
    EAST  = (-1, 1)
    SOUTH = ( 1, 1)
    WEST  = ( 1,-1)
    NORTHEAST = (-1, 0)
    SOUTHEAST = ( 0, 1)
    SOUTHWEST = ( 1, 0)
    NORTHWEST = ( 0,-1)

PREVIEWS = {
    -1:"Special",
    0:"Cursor",
    1:"Movement:End",
    2:"Movement:End",
    DIRECTIONS.NORTHEAST:"Movement:ArrowNE",
    DIRECTIONS.SOUTHEAST:"Movement:ArrowSE",
    DIRECTIONS.SOUTHWEST:"Movement:ArrowSW",
    DIRECTIONS.NORTHWEST:"Movement:ArrowNW",
    #Straight1: NE <-> SW
    (DIRECTIONS.NORTHEAST, DIRECTIONS.NORTHEAST):"Movement:StraightNE",
    (DIRECTIONS.NORTHEAST, DIRECTIONS.SOUTHWEST):"Movement:StraightNE",
    (DIRECTIONS.SOUTHWEST, DIRECTIONS.SOUTHWEST):"Movement:StraightNE",
    (DIRECTIONS.SOUTHWEST, DIRECTIONS.NORTHEAST):"Movement:StraightNE",
    #Straight2: NW <-> SE
    (DIRECTIONS.NORTHWEST, DIRECTIONS.SOUTHEAST):"Movement:StraightNW",
    (DIRECTIONS.NORTHWEST, DIRECTIONS.NORTHWEST):"Movement:StraightNW",
    (DIRECTIONS.SOUTHEAST, DIRECTIONS.SOUTHEAST):"Movement:StraightNW",
    (DIRECTIONS.SOUTHEAST, DIRECTIONS.NORTHWEST):"Movement:StraightNW",
    #Bends
    (DIRECTIONS.NORTHEAST, DIRECTIONS.SOUTHEAST):"Movement:BendN",
    (DIRECTIONS.NORTHWEST, DIRECTIONS.SOUTHWEST):"Movement:BendN",
    (DIRECTIONS.SOUTHEAST, DIRECTIONS.NORTHEAST):"Movement:BendS",
    (DIRECTIONS.SOUTHWEST, DIRECTIONS.NORTHWEST):"Movement:BendS",
    (DIRECTIONS.SOUTHEAST, DIRECTIONS.SOUTHWEST):"Movement:BendE",
    (DIRECTIONS.NORTHEAST, DIRECTIONS.NORTHWEST):"Movement:BendE",
    (DIRECTIONS.SOUTHWEST, DIRECTIONS.SOUTHEAST):"Movement:BendW",
    (DIRECTIONS.NORTHWEST, DIRECTIONS.NORTHEAST):"Movement:BendW",
}
